<?php

	$from = array(
		'Roldanillo [...',
		'Roldanillo pico',
		'borah N',
		'Kerio View H...',
		'Kerio View S...',
		'kerio view',
		'Mt Borah South',
		'Kerio View Sud',
		'kerio',
		'Kerio Süd',
		'Mt. Borah W',
		'zrezane Kerio View',
		'South Kerio',
		'roldanillo',
		'greenacres ...',
		'Greenacres west',
		'Mt. Borah E',
		'Mt. Borah Nor...',
		'Picco, Rolda...',
		'Mt. Bora',
		'Mt. Borah (AU)',
		'mt borah',
		'Mt. Borah S',
		'Roldanillo. ...',
		'El Penon',
		'Mt. Borahh',
		'MT. Borah',
		'Mt. Borah NE',
		'Stella alpina',
		'Bassano [da ...',
		'serrone',
		'garzetta',
		'garzetta gemona',
		'Gemona',
		'bassano',
		'dubbo',
		'Gemona Garzetta Garzette',
		'Serrone 1',
		'Bassano [Ant...',
		'Bassano [Cas...',
		'Barrington Tow',
		'Barrington 3...',
		'Dubbo north',
		'Fanas Eggli',
		'Fiesch Heimatt',
		'Landeck 1',
		'Fiesch [Heimat]',
		'Wildkogel 2',
		'Serrone (IT)',
		'marlens',
		'Bassano - ta...',
		'BASSANO',
		'fanas',
		'Fanas 2',
		'fiesch',
		'riederalp',
		'Quixada',
		'Pena Negra',
		'Piedrahita',
		'Tolmin Kobala',
		'Conargo North',
		'Manilla',
		'greenacres',
		'DeAar',
		'Pampoenfonte...',
		'Roldanillo A...',
		'Barrington\'s...',
		'Barrington t...',
		'quixada',
		'quixada sant...',
		'Quixadá Sant...',
		'DeAar (ZA)',
		'Mt. Borah N',
		'Qixada',
		'Quxada',
		'Morada Nova ...',
		'Mourada Nouva',
		'Mt Borah',
		'col rodella',
		'Kobariski Stol',
		'St. André [...',
		'walts point',
		'Walt\'s Point...',
		'Walt\'s',
		'Fiesch [Heim...',
		'erzincan',
		'Birstonas',
		'Speikboden 2',
		'Speikboden 1',
		'Fiesch heimatt',
		'Fiesch [Galv...',
		'Fiescheralp',
		'piedrahita ',
		'Emberger Alm 1',
		'Birštonas',
		'Rampa Queralt',
		'Fourneuby ',
		'Shumen II',
		'balea n',
		'Balea Lac',
		'Balea N',
		'Jupiter, Utah',
		'speikboden',
		'Antholz 1',
		'Fiesch Heimat',
		'Fiesch Galvera',
		'Niesen - S',
		'defreggen',
		'Kobarid Stoll',
		'Sorica Lajnar',
		'sorica',
		'Michalkow',
		'Cottbus-Nord',
		'Cottbus - Nord',
		'BALDY, ID',
		'Bald mtn sun...',
		'bald mtn sun...',
		'la Breya',
		'Emberger Alm 2',
		'Hohe Wand - Ost',
		'všechov',
		'Všechov - S...',
		'King Mtn Idaho',
		'King Mountai...',
		'SantaRita do...',
		'Kocs Csörl�...',
		'Kalocsa - S',
		'Roldanillo ',
		'sfanta ana',
		'grente',
		'cesaro',
		'Bassano [Pan...',
		'Malý Pěč�...',
		'Emberger Alm 3',
		'balea lac',
		'castelo de vide',
		'corvatch',
		'Flims Casson...',
		'Mount 7',
		'Mt 7 golden',
		'Mt 7',
		'Mt 7 (Golden)',
		'Mt.7 Golden',
		'Mt.7',
		'MT7',
		'Mt. 7',
		'Mt.7-Golden, BC',
		'MT 7',
		'Mt7 Golden',
		'Mount Seven ...',
		'Mt-7 (Golden)',
		'Mount 7 ',
		'Mt. 7 Lookout',
		'Golden',
		'Willi XC Loo...',
		'Mount Seven ',
		'Mount Sevenn',
		'golden',
		'Goldenn',
		'Lookout',
		'Golden ',
		'teton village',
		'Teton villiage',
		'jaragua',
		'Jaragua',
		'Jaraguá Goi...',
		'0',
		'Cerna Hora',
		'Osser - Ostrý',
		'Kruševo E',
		'El Salto ',
		'la Braya',
		'Mackenzie Upper',
		'Upper McKenzie',
		'Upper Macken...',
		'Upper MacKen...',
		'Mt. Seven',
		'Mt Seven',
		'Peña Monta�...',
		'vale de amor...',
		'Vale Amoreira',
		'balea',
		'jupiter',
		'PORXOS',
		'KOnchinka',
		'riederalp (CH)',
		'cavallaria f...',
		'cavallaria',
		'Poggio bustone',
		'Speikboden 3',
		'Gaisberg NO',
		'osterfelder',
		'osterfelder ',
		'Hochrieß',
		'JARACUA',
		'Galibier',
		'Kozakov',
		'Kalocsa - N',
		'Larouco ',
		'Larouco,PT',
		'ROKH',
		'rokh',
		'pebble creek...',
		'Porxos Xc',
		'Porxos xc',
		'Balea N.',
		'Deglėnai',
		'Milk Hill Wh...',
		'la salle ',
		'Linhares da ...',
		'Linhares 1',
		'Olesnica',
		'Mackenzie Lower',
		'Mackenzie',
		'Lower Macken...',
		'Mckenzie',
		'Mt7',
		'Niesen - SW',
		'Fiesch Älpli',
		'Breya',
		'Hinterrugg W',
		'Bischling Ost',
		'Bischling We...',
		'Hebbronville...',
		'Hebronville,...',
		'Hebronnville...',
		'Osterfelder ',
		'Mt Mackenzie...',
		'Lower Mackenzie',
		'Lower MacKenzie',
		'Koclířov -...',
		'PLAN DE LA B...',
		'Jupiter Peak',
		'Narlı, Kahr...',
		'Belltall,ES',
		'rokh NW',
		'Upper MacKenzie',
		'Mt 7 Golden BC',
		'McKenzie ',
		'Montanchez E',
		'Schöckl SO',
		'Wildkogel 1',
		'Feuerkogel N',
		'mein Bischling',
		'antholz',
		'wank',
		'Borsk E',
		' Balea N',
		'Balea E',
		'Nara 2000',
		'moosalp',
		'Kössen 2',
		'Seegrube SW',
		'Col Rodella ...',
		'COL DE L ARP...',
		'fort du truc',
		'oleśnica',
		'Rrokh E',
		'McKenzie - CA',
		'Balea Nord',
		'Bassano tappeti',
		'Saint Hilaire 1',
		'Mackenzie ',
		'McKenzie upper',
		'sunny peak',
		'Feuerkogel N',
		'Emberger',
		'emberger alm',
		'Bassano - Ta...',
		'Bassano casette',
		'Cottbus Nord',
		'serpaton',
		'les richards',
		'Rokh 3angle',
		'sf. ana',
		'Sf Ana',
		'sfânta ana',
		'King mountain',
		'Alliance S/W',
		'Alliance E-W',
		'Alliance E-W...',
		'Galahad E-W',
		'Galahad Tow ...',
		'Galahad EW t...',
		'Gallihad Tow',
		'Galahad tow ...',
		'rampa queralt',
		'Rokh SE',
		'gornergrat',
		'Panarotta - ...',
		'Emberger alm',
		'Gresse-en-ve...',
		'les Richards',
		'Lower MacKen...',
		'McKenzie Lau...',
		'McKenzie low...',
		'Rosslyn W-E',
		'Rosalind E W',
		'cornizzolo',
		'Disentis Lai...',
		'sta maria in...',
		'jeufosse',
		'Houeville',
		'RAMPA QUERALT',
		'Fanas Eggli 2',
		'emberger',
		'Embergeralm',
		'meruz',
		'Méru',
		'Méruz',
		'Zlatník jih',
		'sf ana ',
		'sfanta ana ',
		'Sfanta Ana',
		'agostadero ',
		'Ruederalp',
		'Antholz 2',
		'Bassano Tappeti',
		'loser',
		'LOSER',
		'St Hilaire',
		'Meru',
		'meruz',
		'Les richards',
		'luedingen',
		'rampa Querelt',
		'rampa Queralt',
		'Všechov (CZ)',
		'skrzetla',
		'Emberger Alm...',
		'Elmberger Alm',
		'gefrorene wand',
		'Saint Hilaire 2',
		'St Marcel',
		'meruz ',
		'Queralt ',
		'POLSKA NOWA ...',
		'Braunwald Kiosk',
		'laveno',
		'Turnthaler',
		'Thurtaler',
		'figuerasa',
		'Gemona Garzette',
		'montgellafrey ',
		'garzette gemona',
		'garzette',
		'san giacomo',
		'roldanillo. ...',
		'Mt Borah Nor...',
		'Nyaru ',
		'South Kerio ...',
		'takeoff sud',
		'greeenacres ...',
		'Nyeru Kenya',
		'Hay (north)',
		'Agua Panilla',
		'rift Valley',
		'Kerio view',
		'Borah W',
		'De aar',
		'kerio View',
		'Manilla Mt B...',
		'borah',
		'Mt Borah (Ma...',
		'Mystic, Bright',
		'Mt Borah Man...',
		'Manilla, Aus...',
		'Manilla SE',
		'Mt Borah, Ma...',
		'Garzette Gemona',
		'Billing',
		'Bir',
		'Fiesch Kühb...',
		'Marlens Col ...',
		'billing',
		'Prasher Lake',
		'jot pass',
		'EGED',
		'EGED /HU/',
		'Mein Bischling',
		'MT Borah',
		'iguala',
		'RIEDERALP',
		'Thurnthaler',
		'Turntaler',
		'WILDKOGEL',
		'billing bir',
		'Vsechov',
		'Kobala (SI)',
		'FANAS',
		'Fanas ',
		'FIESCH HEIM',
		'Klosters Got...',
		'gotschna',
		'obere wengi',
		'Schuls',
		'Fiesch (CH)',
		'helm',
		'gemona',
		'S.Giacomo(Fr)',
		'Bassano Camp...',
		'monte nudo',
		'M. Nudo',
		'm.nudo',
		'feltre',
		'Schmitten',
		'thurntaler',
		'Turnthaler, AT',
		'Sillian Thur...',
		'Greifenburg 12',
		'Greifenburg ...',
		'Emberg alm',
		'Iguala (MX)',
		'Birstonas',
		'Manilla (AU)',
		'DOLADA',
		'rubbio',
		'Decollo Rubbio',
		'SCHMITTEN..',
		'Emberger Alm,',
		'Mornera (Mon...',
		'stelzerberg',
		'Ladir',
		'Fanas Eggli ...',
		'OBERE WENGI',
		'obere Wengi',
		'Gummen - Eng...',
		'Eggli',
		'Eggli (CH)',
		'GANA',
		'fiescheralp',
		'gummen (brienz)',
		'W-STEIN',
		'hafelekar',
		'SEEGRUBE',
		'stoderzinken',
		'M.Nudo Laveno',
		'quaggione',
		'hausstein',
		'bisanne',
		'Bissane',
		'meruz ',
		'STOL (SLO)',
		'Kocs',
		'krvavec',
		'bir billing',
		'Mszana 2',
		'SIRIA',
		'Bentelo Plus 4',
		'fanas eggli',
		'Emmberger Alm',
		'Embergeralmiece',
		'Embergerarme...',
		'Gaißberg',
		'Budam Virgen',
		'gastein',
		'Gaisberg SW',
		'juffing',
		'Malga Grente',
		'Oberauer',
		'Oberauersbrunst',
		'vértesszölős',
		'Vértesszölös',
		'Fistengrat',
		'cuarnan gemona',
		'monte nudo l...',
		'wildkogel',
		'cuarnan',
		'm.cuarnan',
		'schöckl SO',
		'Birstonas',
		'Ladir (CH)',
		'Wirzweli Gummen',
		'Brunni Dümp...',
		'Stelser Berg',
		'stelser berg',
		'rideralp',
		'BIBERG',
		'Emberg',
		'Schöckl N',
		'meruz ',
		'Meruz ',
		'Velký Lopen...',
		'nyikom',
		'valkininkai',
		'Fanas eggli',
		'Falzes',
		'falzen',
		'falzes',
		'Platten Pfalzen',
		'gsies',
		'Gsies',
		'Weissenstei',
		'gummenalp',
		'kalocsa',
		'Vetriolo Ter...',
		'panarotta',
		'Monte Panarotta',
		'Seegrube!',
		'ogassa',
		'king mtn idaho',
		'king mountain',
		'Plus 4 - Ben...',
		'mäggisseren',
		'novegno',
		'emberg alm',
		'NIESEN',
		'gummen',
		'Feuerkogel N',
		'aptenau',
		'Trattberg Ab...',
		'Trattberg/ A...',
		'trattberg',
		'Tbtenau Trat...',
		'Trattberg (AT)',
		'Qurnan Gemon...',
		'Gemona Quarnan',
		'hochfelln',
		'HOCHFELLN',
		'Panenský T�...',
		'montgirot',
		'King Mtn. Idaho',
		'Marbachegg T...',
		'niesen',
		'praticino',
		'piedrahita',
		'Cottbus_Nord',
		'Plus4 - Bentelo',
		'Feuerkogel N',
		'Kleines Matt...',
		'les Rchards',
		'denizli',
		'Panukkale',
		'weissenstein',
		'Moosalp,CH',
		'kobala',
		'Soriza',
		'Sorica, Sori...',
		'GEMONA',
		'Eged_track_p...',
		'Toldijk XC M...',
		'Horna Suca',
		'súča',
		'horna suča',
		'Jaragua - BR',
		'castelo',
		'cottbus',
		'karadag',
		'mut',
		'Kavoliai II',
		'Heimatt',
		'Heimat',
		'HEIMATT',
		'Weissenstein...',
		'kapall',
		'pena negra',
		'Pena negra',
		'Peña Negra ...',
		'Piedrahita P...',
		'Pena Negra S...',
		'kocs',
		'balea N',
		'Balea sud',
		'Jaragua-GO',
		'ouro preto d...',
		'Livigno - Ca...',
		'peñanegra',
		'Piedrahita (ES)',
		'Peñanegra',
		'Piedrahitab',
		'Chelan',
		'Eger-Eged',
		'horna suca',
		'Súča',
		'inovec',
		'Jaragua - Go',
		'Jaragua - GO',
		'poggio bustone',
		'CORNIZZOLO',
		'Speickboden',
		'prada del mo...',
		'quarnan gemona',
		'Feuerkogel S',
		'Pena',
		'Jaraguá - GO',
		'Pine Mtn',
		'PineMtn',
		'Queral',
		'penya montan...',
		'Rampa de Que...',
		'Mt. 7 Golden',
		'Moosalp aka ...',
		'fiesch heimat',
		'SORICA',
		'csobanc',
		'leonpolis',
		'Peña Monta...',
		'FIESCH',
		'Flims Cassons',
		'Cassonsgrat',
		'Fiesch - Kü...',
		'fiesch heimatt',
		'Kueboden',
		'Ayas, Ankara',
		'fiesch Heimat',
		'Kuhboden',
		'monte Grappa',
		'Cima Grappa ...',
		'cima grappa',
		'Mt.Grappa',
		'Speikboden, ...',
		'Spikeboudn',
		'Nove Sady',
		'schmitten',
		'Defreggen',
		'Teton Villag...',
		'Balea Lacut ...',
		'Kühboden',
		'Fiescheralp,...',
		'Fiesch, Chü...',
		'Slovenia Kobala',
		'golm',
		'Deffregen',
		'Hearne, TX',
		'Hearne, TX USA',
		'hearne, TX USA',
		'Jupiter Peak...',
		'Skinny Ridge...',
		'gardane rokh',
		'Sfanta Ana',
		'speickboden',
		'Fiesch, Heimat',
		'Fiescheralp ...',
		'FIESCH SM1',
		'Fiesch, Küe...',
		'Fiesch garvela',
		'Fiesch Kühe...',
		'Seegrube (AT)',
		'Defreggen',
		'kobata',
		'Bald Mountain',
		'Bald Mountai...',
		'Mount Baldy,...',
		'Bald mtn. Su...',
		'Michalków',
		'Bisanne (Sig...',
		'speikpoden',
		'davos',
		'birstonas',
		'Birstonas',
		'Ottawa, KS',
		'Bald, Sun Va...',
		'sopot (BG)',
		'Mirandela W',
		'corvatsch',
		'Piz Corvatsch',
		'bald mtn. Su...',
		'Balea S',
		'Walts Point',
		'Bir-Billing',
		'Quixada Rampa',
		'Mt Bakewell',
		'Bakewell',
		'Barr South',
		'Quixada Sant...',
		'De Aar ',
		'de aar',
		'Serra Talhad...',
		'Serra Telhada',
		'Serra Telhad...',
		'de Aar',
		'De Aar - Vos...',
		'DeAar - Vosburg',
		'Branvlei',
		'Priska',
		'Riacho das A...',
		'Booligal, NSW',
		'mirador de l...',
		'mirador',
		'Greenacres West',
		'Barrington No.3',
		'South Barrin...',
		'Araripina Ai...',
		'Roldanillo Pico',
		'Ivanhoe Airs...',
		'Kakamas Airf...',
		'porterville',
		'kerio view h...'
	);
	$to = array(
		'Roldanillo',
		'Roldanillo',
		'Mt. Borah',
		'Kerio View',
		'Kerio View',
		'Kerio View',
		'Mt. Borah',
		'Kerio View',
		'Kerio View',
		'Kerio View',
		'Mt. Borah',
		'Kerio View',
		'Kerio View',
		'Roldanillo',
		'Greenacres',
		'Greenacres',
		'Mt. Borah',
		'Mt. Borah',
		'Roldanillo Pico',
		'Mt. Borah',
		'Mt. Borah',
		'Mt. Borah',
		'Mt. Borah',
		'Roldanillo',
		'El Peñon',
		'Mt. Borah',
		'Mt. Borah',
		'Mt. Borah',
		'Stella Alpina',
		'Bassano',
		'Serrone',
		'Gemona',
		'Gemona',
		'Gemona',
		'Bassano',
		'Dubbo',
		'Gemona',
		'Serrone',
		'Bassano',
		'Bassano',
		'Barrington',
		'Barrington',
		'Dubbo',
		'Fanas',
		'Fiesch',
		'Landeck',
		'Fiesch',
		'Wildkogel',
		'Serrone',
		'Marlens',
		'Bassano',
		'Bassano',
		'Fanas',
		'Fanas',
		'Fiesch',
		'Riederalp',
		'Quixadá',
		'Peña Negra',
		'Peña Negra',
		'Kobala',
		'Conargo',
		'Mt. Borah',
		'Greenacres',
		'De Aar',
		'Pampoenfontein',
		'Roldanillo',
		'Barrington',
		'Barrington',
		'Quixadá',
		'Quixadá',
		'Quixadá',
		'De Aar',
		'Mt. Borah',
		'Quixadá',
		'Quixadá',
		'Morada Nova',
		'Morada Nova',
		'Mt. Borah',
		'Col Rodella',
		'Stol',
		'St. André',
		'Walt\'s Point',
		'Walt\'s Point',
		'Walt\'s Point',
		'Fiesch',
		'Erzincan',
		'Birštonas',
		'Speikboden',
		'Speikboden',
		'Fiesch',
		'Fiesch',
		'Fiesch',
		'Peña Negra',
		'Emberger Alm',
		'Birstonas',
		'Queralt',
		'Fourneuby',
		'Shumen',
		'Balea',
		'Balea',
		'Balea',
		'Jupiter',
		'Speikboden',
		'Antholz',
		'Fiesch',
		'Fiesch',
		'Niesen',
		'Defreggen',
		'Stol',
		'Sorica',
		'Sorica',
		'Michalków',
		'Cottbus',
		'Cottbus',
		'Mt. Baldy',
		'Mt. Baldy',
		'Mt. Baldy',
		'La Breya',
		'Emberger Alm',
		'Hohe Wand',
		'Všechov',
		'Všechov',
		'King Mountain',
		'King Mountain',
		'Santa Rita d...',
		'Kocs Csörl...',
		'Kalocsa',
		'Roldanillo',
		'Sfanta Ana',
		'Grente',
		'Cesarò',
		'Bassano',
		'Malý Pěč...',
		'Emberger Alm',
		'Balea',
		'Castelo de V...',
		'Piz Corvatsch',
		'Cassons',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Mount Seven',
		'Teton Village',
		'Teton Village',
		'Jaraguá',
		'Jaraguá',
		'Jaraguá',
		'Jaraguá',
		'Černá Hora',
		'Osser',
		'Kruševo',
		'El Salto',
		'La Breya',
		'McKenzie',
		'McKenzie',
		'McKenzie',
		'McKenzie',
		'Mount Seven',
		'Mount Seven',
		'Peña Monta...',
		'Vale de Amor...',
		'Vale de Amor...',
		'Balea',
		'Jupiter',
		'Porxos',
		'Konchinka',
		'Riederalp',
		'Cavallaria',
		'Cavallaria',
		'Poggio Bustone',
		'Speikboden',
		'Gaisberg',
		'Osterfelder',
		'Osterfelder',
		'Hochries',
		'Jaraguá',
		'Col du Galibier',
		'Kozákov',
		'Kalocsa',
		'Larouco',
		'Larouco',
		'Rokh',
		'Rokh',
		'Pebble Creek...',
		'Porxos',
		'Porxos',
		'Balea',
		'Deglenai',
		'Milk Hill',
		'La Salle',
		'Linhares',
		'Linhares',
		'Oleśnica',
		'McKenzie',
		'McKenzie',
		'McKenzie',
		'McKenzie',
		'Mount Seven',
		'Niesen',
		'Fiesch',
		'La Breya',
		'Hinterrugg',
		'Bischling',
		'Bischling',
		'Hebbronville',
		'Hebbronville',
		'Hebbronville',
		'Osterfelder',
		'McKenzie',
		'McKenzie',
		'McKenzie',
		'Koclířov',
		'Plan de la B...',
		'Jupiter',
		'Narli',
		'Belltall',
		'Rokh',
		'McKenzie',
		'Mount Seven',
		'McKenzie',
		'Montanchez',
		'Schöckl',
		'Wildkogel',
		'Feuerkogel N',
		'Bischling',
		'Antholz',
		'Wank',
		'Borsk',
		'Balea',
		'Balea',
		'Nara',
		'Moosalp',
		'Kössen',
		'Seegrube',
		'Col Rodella',
		'Col de l\'Arp...',
		'Fort du Truc',
		'Oleśnica',
		'Rokh',
		'McKenzie',
		'Balea',
		'Bassano',
		'Saint Hilaire',
		'McKenzie',
		'McKenzie',
		'Sun Peak',
		'Feuerkogel',
		'Emberger Alm',
		'Emberger Alm',
		'Bassano',
		'Bassano',
		'Cottbus',
		'Serpaton',
		'Les Richards',
		'Rokh',
		'Sf. Ana',
		'Sf. Ana',
		'Sf. Ana',
		'King Mountain',
		'Alliance',
		'Alliance',
		'Alliance',
		'Galahad',
		'Galahad',
		'Galahad',
		'Galahad',
		'Galahad',
		'Queralt',
		'Rokh',
		'Gornergrat',
		'Panarotta',
		'Emberger Alm',
		'Gresse en Ve...',
		'Les Richards',
		'McKenzie',
		'McKenzie',
		'McKenzie',
		'Rosalind',
		'Rosalind',
		'Cornizzolo',
		'Lai Alf',
		'Sta Maria in...',
		'Jeufosse',
		'Houéville',
		'Queralt',
		'Fanas',
		'Emberger Alm',
		'Emberger Alm',
		'Meruz',
		'Meruz',
		'Meruz',
		'Zlatník',
		'Sf. Ana',
		'Sf. Ana',
		'Sf. Ana',
		'agostadero',
		'Riederalp',
		'Antholz',
		'Bassano',
		'Loser',
		'Loser',
		'Saint Hilaire',
		'Meruz',
		'Meruz',
		'Les Richards',
		'Lüdingen',
		'Queralt',
		'Queralt',
		'Všechov',
		'Skrzętla',
		'Emberger Alm',
		'Emberger Alm',
		'Gefrorene Wand',
		'Saint Hilaire',
		'Saint-Marcel',
		'Meruz',
		'Queralt',
		'Polska Nowa ...',
		'Braunwald',
		'Laveno',
		'Thurntaler',
		'Thurntaler',
		'Figuerassa',
		'Gemona',
		'montgellafrey',
		'Gemona',
		'Gemona',
		'San Giacomo',
		'Roldanillo',
		'Mt. Borah',
		'Nyaru',
		'Kerio View',
		'Kerio View',
		'Greenacres',
		'Nyaru',
		'Hay',
		'Agua Panela',
		'Kerio View',
		'Kerio View',
		'Mt. Borah',
		'De Aar',
		'Kerio View',
		'Mt. Borah',
		'Mt. Borah',
		'Mt. Borah',
		'Mystic',
		'Mt. Borah',
		'Mt. Borah',
		'Mt. Borah',
		'Mt. Borah',
		'Gemona',
		'Bir Billing',
		'Bir Billing',
		'Fiesch',
		'Marlens',
		'Bir Billing',
		'prashar lake',
		'Jot Pass',
		'Eged',
		'Eged',
		'Bischling',
		'Mt. Borah',
		'Iguala',
		'Riederalp',
		'Thurntaler',
		'Thurntaler',
		'Wildkogel',
		'Bir Billing',
		'Všechov',
		'Kobala',
		'Fanas',
		'Fanas',
		'Fiesch',
		'Gotschna',
		'Gotschna',
		'Obere Wengi',
		'Scuol',
		'Fiesch',
		'Helm',
		'Gemona',
		'San Giacomo',
		'Bassano',
		'Laveno',
		'Laveno',
		'Laveno',
		'Feltre',
		'Schmittenhöhe',
		'Thurntaler',
		'Thurntaler',
		'Thurntaler',
		'Greifenburg',
		'Greifenburg',
		'Emberger Alm',
		'Iguala',
		'Birštonas',
		'Mt. Borah',
		'Monte Dolada',
		'Rubbio',
		'Rubbio',
		'Schmittenhöhe',
		'Emberger Alm',
		'Mornera',
		'Stelserberg',
		'Ladir',
		'Fanas',
		'Obere Wengi',
		'Obere Wengi',
		'Gummen',
		'Fanas',
		'Fanas',
		'Gana',
		'Fiesch',
		'Gummen',
		'Weissenstein',
		'Hafelekar',
		'Seegrube',
		'Stoderzinken',
		'Laveno',
		'Quaggione',
		'Hausstein',
		'Bisanne',
		'Bisanne',
		'Meruz',
		'Stol',
		'Kocs Csörl...',
		'Krvavec',
		'Bir Billing',
		'Mszana',
		'Siria',
		'Bentelo',
		'Fanas',
		'Emberger Alm',
		'Emberger Alm',
		'Emberger Alm',
		'Gaisberg',
		'Virgen Budam',
		'Gastein',
		'Gaisberg',
		'Jufing',
		'Grente',
		'Oberauer Brunst',
		'Oberauer Brunst',
		'Vértesszőlős',
		'Vértesszőlős',
		'Fisetengrat',
		'Gemona',
		'Laveno',
		'Wildkogel',
		'Cuarnan',
		'Cuarnan',
		'Schöckl',
		'Birštonas',
		'Ladir',
		'Gummen',
		'Brunni',
		'Stelserberg',
		'Stelserberg',
		'Riederalp',
		'Biberg',
		'Emberger Alm',
		'Schöckl',
		'Meruz',
		'Velky Lopenik',
		'Nyikom',
		'Valkininkai',
		'Fanas',
		'Pfalzen',
		'Pfalzen',
		'Pfalzen',
		'Pfalzen',
		'Uwaldalm Gsies',
		'Uwaldalm Gsies',
		'Weissenstein',
		'Gummen',
		'Kalocsa',
		'Vetriolo Terme',
		'Panarotta',
		'Panarotta',
		'Seegrube',
		'Ogassa',
		'King Mountain',
		'King Mountain',
		'Bentelo',
		'Mäggisseren',
		'Novegno',
		'Emberger Alm',
		'Niesen',
		'Gummen',
		'Feuerkogel',
		'Aptenau',
		'Trattberg',
		'Trattberg',
		'Trattberg',
		'Trattberg',
		'Trattberg',
		'Trattberg',
		'Gemona',
		'Gemona',
		'Hochfelln',
		'Hochfelln',
		'Panenský T...',
		'Montgirot',
		'King Mountain',
		'Marbachegg',
		'Niesen',
		'Praticino',
		'Peña Negra',
		'Cottbus',
		'Bentelo',
		'Feuerkogel',
		'Klein Matter...',
		'Les Richards',
		'Denizli',
		'Pamukkale',
		'Weissenstein',
		'Moosalp',
		'Kobala',
		'Sorica',
		'Sorica',
		'Gemona',
		'Eged',
		'Toldijk',
		'Horná Súča',
		'Horná Súča',
		'Horná Súča',
		'Jaraguá',
		'Castelo De Vide',
		'Cottbus',
		'Karadag',
		'Mut',
		'Kavoliai',
		'Fiesch',
		'Fiesch',
		'Fiesch',
		'Weissenstein',
		'Kapall',
		'Peña Negra',
		'Peña Negra',
		'Peña Negra',
		'Peña Negra',
		'Peña Negra',
		'Kocs Csörl...',
		'Balea',
		'Balea',
		'Jaraguá',
		'Ouro Preto D...',
		'Livigno',
		'Peña Negra',
		'Peña Negra',
		'Peña Negra',
		'Peña Negra',
		'Chelan Butte',
		'Eged',
		'Horná Súča',
		'Horná Súča',
		'Inovec',
		'Jaraguá',
		'Jaraguá',
		'Poggio Bustone',
		'Cornizzolo',
		'Speikboden',
		'Prada',
		'Gemona',
		'Feuerkogel',
		'Peña Negra',
		'Jaraguá',
		'Pine Mt',
		'Pine Mt',
		'Queralt',
		'Peña Negra',
		'Queralt',
		'Mount Seven',
		'Moosalp',
		'Fiesch',
		'Sorica',
		'Csobánc',
		'Leonpolis',
		'Peña Negra',
		'Fiesch',
		'Cassons',
		'Cassons',
		'Fiesch',
		'Fiesch',
		'Fiesch',
		'Ayaş',
		'Fiesch',
		'Fiesch',
		'Bassano',
		'Bassano',
		'Bassano',
		'Bassano',
		'Speikboden',
		'Speikboden',
		'Nové Sady',
		'Schmittenhö...',
		'Defereggen',
		'Teton Village',
		'Balea',
		'Fiesch',
		'Fiesch',
		'Fiesch',
		'Kobala',
		'Golm',
		'Defereggen',
		'Hearne',
		'Hearne',
		'Hearne',
		'Jupiter',
		'Skinny Ridge',
		'Rokh',
		'Sf. Ana',
		'Speikboden',
		'Fiesch',
		'Fiesch',
		'Fiesch',
		'Fiesch',
		'Fiesch',
		'Fiesch',
		'Seegrube',
		'Defereggen',
		'Kobala',
		'Mt. Baldy',
		'Mt. Baldy',
		'Mt. Baldy',
		'Mt. Baldy',
		'Michałków',
		'Bisanne',
		'Speikboden',
		'Davos',
		'Birštonas',
		'Birštonas',
		'Ottawa',
		'Mt. Baldy',
		'Sopot',
		'Mirandela',
		'Corvatsch',
		'Corvatsch',
		'Mt. Baldy',
		'Balea',
		'Walt\'s Point',
		'Bir Billing',
		'Quixadá',
		'Mt. Bakewell',
		'Mt. Bakewell',
		'Barrington',
		'Quixadá',
		'De Aar',
		'De Aar',
		'Serra Talhada',
		'Serra Talhada',
		'Serra Talhada',
		'De Aar',
		'De Aar',
		'De Aar',
		'Brandvlei',
		'Prieska',
		'Riacho des A...',
		'Booligal',
		'Mirador De L...',
		'Mirador De L...',
		'Greenacres',
		'Barrington',
		'Barrington',
		'Araripina',
		'Roldanillo',
		'Ivanhoe',
		'Kakamas',
		'Porterville',
		'Kerio View'
	);
	
foreach($from as $k => $v){
	echo $v.' -> '.$to[$k].'<br />';
}